# This file is automatically generated by pyo3_stub_gen

import typing

from nautilus_trader import model
from nautilus_trader.adapters.projectx.backtest import (
    ProjectXCatalogDownloadResult as ProjectXCatalogDownloadResult,
)
from nautilus_trader.adapters.projectx.backtest import (
    build_external_bar_type as build_external_bar_type,
)
from nautilus_trader.adapters.projectx.backtest import (
    download_bars_to_catalog as download_bars_to_catalog,
)
from nautilus_trader.adapters.projectx.backtest import (
    download_bars_to_catalog_async as download_bars_to_catalog_async,
)
from nautilus_trader.adapters.projectx.providers import (
    ProjectXInstrumentProvider as ProjectXInstrumentProvider,
)

__all__ = [
    "PROJECTX",
    "PROJECTX_CLIENT_ID",
    "PROJECTX_VENUE",
    "ProjectXCatalogDownloadResult",
    "ProjectXConfig",
    "ProjectXDataClientConfig",
    "ProjectXDataClientFactory",
    "ProjectXExecClientConfig",
    "ProjectXExecutionClientFactory",
    "ProjectXHttpClient",
    "ProjectXInstrumentProvider",
    "build_external_bar_type",
    "databento_to_projectx_adapter_symbol",
    "databento_to_projectx_contract_id",
    "download_bars_to_catalog",
    "download_bars_to_catalog_async",
    "load_projectx_env",
    "projectx_to_databento_symbol",
    "projectx_to_databento_symbol_with_year",
    "projectx_to_rithmic_symbol",
    "rithmic_to_projectx_symbol",
    "rithmic_to_projectx_symbol_with_year",
]

PROJECTX: str
PROJECTX_CLIENT_ID: model.ClientId
PROJECTX_VENUE: model.Venue

@typing.final
class ProjectXConfig:
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def retry_delay_initial_ms(self) -> int: ...
    @property
    def retry_delay_max_ms(self) -> int: ...
    @property
    def http_proxy_url(self) -> str | None: ...
    def __init__(
        self,
        environment: str | None = None,
        user_name: str | None = None,
        api_key: str | None = None,
        http_timeout_secs: int | None = None,
        max_retries: int | None = None,
        retry_delay_initial_ms: int | None = None,
        retry_delay_max_ms: int | None = None,
        http_proxy_url: str | None = None,
    ) -> None: ...

@typing.final
class ProjectXDataClientConfig:
    @property
    def transport(self) -> ProjectXConfig: ...
    @property
    def market_data_live(self) -> bool: ...
    def __init__(
        self,
        environment: str | None = None,
        user_name: str | None = None,
        api_key: str | None = None,
        http_timeout_secs: int | None = None,
        max_retries: int | None = None,
        retry_delay_initial_ms: int | None = None,
        retry_delay_max_ms: int | None = None,
        http_proxy_url: str | None = None,
        market_data_live: bool = False,
    ) -> None: ...

@typing.final
class ProjectXDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class ProjectXExecClientConfig:
    @property
    def trader_id(self) -> model.TraderId: ...
    @property
    def account_id(self) -> model.AccountId: ...
    @property
    def account_type(self) -> model.AccountType: ...
    @property
    def transport(self) -> ProjectXConfig: ...
    def __init__(
        self,
        trader_id: str,
        account_id: str,
        environment: str | None = None,
        user_name: str | None = None,
        api_key: str | None = None,
        http_timeout_secs: int | None = None,
        max_retries: int | None = None,
        retry_delay_initial_ms: int | None = None,
        retry_delay_max_ms: int | None = None,
        http_proxy_url: str | None = None,
        account_type: model.AccountType | None = None,
    ) -> None: ...

@typing.final
class ProjectXExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class ProjectXHttpClient:
    def __init__(self, config: ProjectXConfig) -> None: ...
    @staticmethod
    def from_config(config: ProjectXConfig) -> ProjectXHttpClient: ...
    @property
    def api_base_url(self) -> str: ...
    @property
    def rtc_base_url(self) -> str: ...
    def stop(self) -> None: ...
    def start(self) -> typing.Any: ...
    def authenticate(self) -> typing.Any: ...
    def validate(self) -> typing.Any: ...
    def retrieve_bars(
        self,
        contract_id: str,
        bar_type: model.BarType,
        start_time: str,
        end_time: str,
        unit: int | None = None,
        unit_number: int | None = None,
        limit: int = 500,
        live: bool = False,
        include_partial_bar: bool = False,
        allow_live_history_fallback: bool = False,
    ) -> typing.Any: ...
    def resolve_front_month_instrument(
        self, product_root: str, live: bool = False
    ) -> typing.Any: ...
    def contract_by_id(self, contract_id: str) -> typing.Any: ...
    def available_instruments(
        self, live: bool = False, active_only: bool = False, product_root: str | None = None
    ) -> typing.Any: ...

def databento_to_projectx_adapter_symbol(symbol: str) -> str: ...
def databento_to_projectx_contract_id(symbol: str) -> str: ...
def load_projectx_env(path: str | None = None, override_existing: bool = False) -> int: ...
def projectx_to_databento_symbol(symbol: str) -> str: ...
def projectx_to_databento_symbol_with_year(symbol: str, reference_year: int) -> str: ...
def projectx_to_rithmic_symbol(symbol: str) -> str: ...
def rithmic_to_projectx_symbol(symbol: str) -> str: ...
def rithmic_to_projectx_symbol_with_year(symbol: str, reference_year: int) -> str: ...
